---
title: "Getting Started" 
author: "<h4>Authors: <i>`r auths <- eval(parse(text = gsub('person','c',read.dcf('../DESCRIPTION', fields = 'Authors@R'))));paste(auths[names(auths)=='given'],auths[names(auths)=='family'], collapse = ', ')`</i></h4>" 
date: "<h4>Vignette updated: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{templateR} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup}
library(echoLD)

query_dat <- echodata::BST1[seq(1,100),]
locus_dir <- file.path(tempdir(), echodata::locus_dir)
```


# 1000 Genomes: Phase 1 or 3

```{r}
LD_1kgp3 <- echoLD::get_LD(locus_dir = locus_dir,
                           query_dat = query_dat,
                           LD_reference = "1KGphase3") # 1KGphase1
```

## Plot

```{r}
echoLD::plot_LD(LD_matrix = LD_1kgp3$LD, 
                query_dat = LD_1kgp3$DT,
                span = 20)
```


# UK Biobank

*WARNING*: Takes substantially longer than 1000 Genomes methods.

```{r, eval=FALSE}
LD_ukb <- echoLD::get_LD(locus_dir = locus_dir,
                         query_dat = query_dat,
                         LD_reference = "UKB", 
                         download_method = "axel", 
                         nThread = 10)
```

## Plot

```{r, eval=FALSE}
echoLD::plot_LD(LD_matrix = LD_ukb$LD, 
                query_dat = LD_ukb$DT,
                span = 20)
```


# Custom VCF

```{r}
LD_reference <- system.file("extdata","BST1.1KGphase3.vcf.bgz", 
                            package = "echodata")
samples <- c("HG00097","HG00099","HG00100","HG00101","HG00102")
LD_custom <- echoLD::get_LD(locus_dir = locus_dir,
                            query_dat = query_dat, 
                            LD_reference = LD_reference)
```

## Plot

```{r, eval=FALSE}
echoLD::plot_LD(LD_matrix = LD_custom$LD, 
                query_dat = LD_custom$DT,
                span = 20)
```

# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

<br>
